//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFingerPrint
    {
        public System.Guid FingerPrintId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string LeftThumb { get; set; }
        public string LeftIndexFinger { get; set; }
        public string LeftMiddleFinger { get; set; }
        public string LeftRingFinger { get; set; }
        public string LeftBabyFinger { get; set; }
        public string RightThumb { get; set; }
        public string RightIndexFinger { get; set; }
        public string RightMiddleFinger { get; set; }
        public string RightRingFinger { get; set; }
        public string RightBabyFinger { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
