//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPoliticalInformation
    {
        public System.Guid PoliticalInformationId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string PoliceStation { get; set; }
        public string PostOffice { get; set; }
        public string AreaNazimName { get; set; }
        public string WellKnownPerson { get; set; }
        public string UCNo { get; set; }
        public string NANumber { get; set; }
        public string PANumber { get; set; }
        public string VoteNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
