//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSalaryDetail
    {
        public System.Guid SalaryDetailsId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public Nullable<int> BasicSalary { get; set; }
        public Nullable<int> DutyBouns { get; set; }
        public Nullable<int> WeaponAllowance { get; set; }
        public Nullable<int> AnnualLeaves { get; set; }
        public Nullable<int> Contract { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
