//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTransferHistory
    {
        public System.Guid TransferHistoryId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string OTSegment { get; set; }
        public string OTSubSegment { get; set; }
        public string OTDepartSegment { get; set; }
        public string OTJob { get; set; }
        public string OTManager { get; set; }
        public string OTCoach { get; set; }
        public string OTCenter { get; set; }
        public string NTSegment { get; set; }
        public string NTSubSegment { get; set; }
        public string NTDepartSegment { get; set; }
        public string NTJob { get; set; }
        public string NTManager { get; set; }
        public string NTCoach { get; set; }
        public string NTCenter { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
