//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Vew_Employee
    {
        public System.Guid EmployeeId { get; set; }
        public System.Guid SegmentId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CNIC { get; set; }
        public string FatherName { get; set; }
        public string FatherCNIC { get; set; }
        public string PermanentAddress { get; set; }
        public string CurrentAddress { get; set; }
        public string ProfilePicture { get; set; }
        public string Phone { get; set; }
        public string MotherName { get; set; }
        public string Education { get; set; }
        public string BloodGroup { get; set; }
        public string IdentificationMarks { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string NextToKIN { get; set; }
        public string WifeName { get; set; }
        public Nullable<int> NoOfChilds { get; set; }
        public Nullable<int> NoOfBoys { get; set; }
        public Nullable<int> NoOfGirls { get; set; }
        public Nullable<byte> Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.Guid> ArmyInformationId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string UnitName { get; set; }
        public string ForceNo { get; set; }
        public string LastUnit { get; set; }
        public string LastCenter { get; set; }
        public Nullable<int> ServicePeriod { get; set; }
        public string RecordCenter { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public string Rank { get; set; }
        public string Trade { get; set; }
        public string ForceType { get; set; }
        public string PreviousForces { get; set; }
        public Nullable<System.Guid> BankDetailsId { get; set; }
        public string BankName { get; set; }
        public string AccountTitle { get; set; }
        public string AccountNo { get; set; }
        public string BranchName { get; set; }
        public string AccountOwner { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.Guid> EmergencyContactId { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmergencyPhone { get; set; }
        public string EmergencyCell { get; set; }
        public Nullable<System.Guid> FingerPrintId { get; set; }
        public string LeftThumb { get; set; }
        public string LeftIndexFinger { get; set; }
        public string LeftMiddleFinger { get; set; }
        public string LeftRingFinger { get; set; }
        public string LeftBabyFinger { get; set; }
        public string RightThumb { get; set; }
        public string RightIndexFinger { get; set; }
        public string RightMiddleFinger { get; set; }
        public string RightRingFinger { get; set; }
        public string RightBabyFinger { get; set; }
        public Nullable<System.Guid> PoliticalInformationId { get; set; }
        public string PoliceStation { get; set; }
        public string PostOffice { get; set; }
        public string AreaNazimName { get; set; }
        public string WellKnownPerson { get; set; }
        public string UCNo { get; set; }
        public string NANumber { get; set; }
        public string PANumber { get; set; }
        public string VoteNo { get; set; }
        public Nullable<System.Guid> RejoinHistoryId { get; set; }
        public Nullable<System.DateTime> PreviousAppointmentDate { get; set; }
        public Nullable<System.DateTime> PreviousTerminateDate { get; set; }
        public Nullable<System.DateTime> RejoinDate { get; set; }
        public Nullable<System.Guid> SalaryDetailsId { get; set; }
        public Nullable<int> BasicSalary { get; set; }
        public Nullable<int> DutyBouns { get; set; }
        public Nullable<int> WeaponAllowance { get; set; }
        public Nullable<int> AnnualLeaves { get; set; }
        public Nullable<int> Contract { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
        public string OTSegment { get; set; }
        public string OTSubSegment { get; set; }
        public string OTDepartSegment { get; set; }
        public string OTJob { get; set; }
        public string OTManager { get; set; }
        public string OTCoach { get; set; }
        public string OTCenter { get; set; }
        public string NTSegment { get; set; }
        public string NTSubSegment { get; set; }
        public string NTDepartSegment { get; set; }
        public string NTJob { get; set; }
        public string NTManager { get; set; }
        public string NTCoach { get; set; }
        public string NTCenter { get; set; }
        public Nullable<System.Guid> RegionId { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public Nullable<System.Guid> CenterId { get; set; }
        public string CenterName { get; set; }
        public string RegionHead { get; set; }
        public string SupervisorName { get; set; }
        public Nullable<System.Guid> PostId { get; set; }
        public string PostName { get; set; }
        public Nullable<System.Guid> SupervisorId { get; set; }
        public string EmployeeType { get; set; }
    }
}
