//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public System.Guid PostId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> DeploymentDate { get; set; }
        public Nullable<System.Guid> CenterId { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string PostName { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> ReceivedBy { get; set; }
        public string MediumReference { get; set; }
        public Nullable<System.Guid> Coordinator { get; set; }
        public Nullable<System.Guid> Supervisor { get; set; }
        public Nullable<bool> PaidOn { get; set; }
        public Nullable<int> ProposedSalaryRate { get; set; }
        public Nullable<int> InvoiceRate { get; set; }
        public string GuardCategory { get; set; }
        public Nullable<int> NoOfSG { get; set; }
        public Nullable<int> ProjectStrengthAfetDeployment { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
